---
- name: Configure NTP on all servers
  hosts: all
  become: yes
  vars:
    ntp_servers:
      - 0.pool.ntp.org
      - 1.pool.ntp.org
      - 2.pool.ntp.org
      - 3.pool.ntp.org

  tasks:
    - name: Install chrony (NTP client)
      ansible.builtin.package:
        name: chrony
        state: present

    - name: Configure chrony
      ansible.builtin.copy:
        dest: /etc/chrony/chrony.conf
        content: |
          pool {{ ntp_servers[0] }} iburst
          pool {{ ntp_servers[1] }} iburst
          pool {{ ntp_servers[2] }} iburst
          pool {{ ntp_servers[3] }} iburst
          driftfile /var/lib/chrony/drift
          makestep 1.0 3
          rtcsync
          keyfile /etc/chrony/chrony.keys
          leapsectz right/UTC
          logdir /var/log/chrony

      notify: Restart chrony

    - name: Ensure chrony is running and enabled
      ansible.builtin.service:
        name: chrony
        state: started
        enabled: yes

  handlers:
    - name: Restart chrony
      ansible.builtin.service:
        name: chrony
        state: restarted
